# name: Test
# on:
#   push:
#     branches:
#       - master
# jobs:
#   test:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@master
#       - name: Install Dependencies
#         run: yarn install --frozen-lockfile
#       - name: Run Test
#         run: yarn test:coverage
#       - name: Upload Coverage
#         uses: codecov/codecov-action@v1.0.13
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}